# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/Downloads/Hex2SevenSegConverter .vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/Downloads/SevenSeg_Top .vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/alu.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/control_unit.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/Downloads/debounce.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/dmem.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/header_pk.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/imem.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/register_file.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/new/uart_parity.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/new/uart_tx.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/new/uart_rx.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/new/uart.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/imports/new/uart_wrapper2.vhd}
  {C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/sources_1/new/mips_top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/constrs_1/imports/constrs_1/imports/temp2/nexsys4_ddr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/milin_/Desktop/Advanced Computer Hardware Design/Mips_processorUARTAlphav2/Mips_processorUARTAlphav2.srcs/constrs_1/imports/constrs_1/imports/temp2/nexsys4_ddr.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mips_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_top_utilization_synth.rpt -pb mips_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
